name: Build Android APK

on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload artifacts (APK)
        uses: actions/upload-artifact@v4  # <-- اینجا تغییر داده شد
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
